config/routes.rb
Onesheet::Application.routes.draw do

  
 
    
  resources :statuses

  root :to => "events#week"
  
  resources :venues do
    collection do
      
    end
    
    member do
    end
    
    resources :events do
      collection do
        get :today
        get :week
      end
    end
  
  end
  
  resources :events do
    collection do
      get :today
      get :scrape
      get :week
    end
    member do
    end
  end
  
  
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
require 'open-uri'
class Event < ActiveRecord::Base
  ActiveRecord::Base.inheritance_column = "activerecordtype" 
  
  after_initialize :default_values

  
  belongs_to :venue
  
  scope :by_venue, lambda{ |venue_id|
    where("events.venue_id = ?", venue_id)
  }
  
  scope :today, lambda{
    where("events.begins_at >= ? and events.begins_at < ?", Date.today, Date.today+1 )
  }
  
  scope :week, lambda{
    where("events.begins_at >= ? and events.begins_at <= ? ", Date.today, Date.today+7 )
  }
  
  scope :past, lambda{
    where("events.begins_at < ?", Date.today.to_s(:db))
  }

  scope :all_upcoming, lambda{
    where("events.begins_at >= ?", Date.today.to_s(:db))
  }
  
  scope :unconfirmed, lambda{
    where("events.confirmed = ?", 0)
  }
  
  scope :confirmed, lambda{
    where("events.confirmed = ?", 1)
  }

  scope :stale, lambda{
    where("events.state = ?", "stale")
  }

  scope :fresh, lambda{ 
    where("events.state = ?", "new")
  }

  scope :changed, lambda{ 
    where("events.state = ?", "updated")
  }
  
  state_machine :state, :initial => :new do
    
    event :examine do
      transition [:new, :updated] => :stale
    end

    event :change do
      transition [:new, :stale, :updated] => :updated
    end


    state :new do
      def fresh?
        true
      end
    end
  end

  def self.collect_events
    p 'Lets get scrapin!'
    venues = Venue.all
    results =[]
    venues.each {|venue|
      Event.const_get(venue.parse_type.to_sym).gather(venue)
    }

  end
  
  class GigPress
    def self.gather(venue)
      @events = []

      Nokogiri::XML(open(venue.event_list_url)).xpath("//item").map do |item|
        scratch = Event.create!

        scratch.name =  item.xpath("title").text
        scratch.description = Event.xml_wrap(item, 'Notes')
        date = Event.xml_wrap(item, 'Date')
        time = Event.xml_wrap(item, 'Time')
        scratch.begins_at = DateTime.parse("#{date} #{time}")
        scratch.price = Event.xml_wrap(item, 'Admission')
        scratch.age_restriction = Event.xml_wrap(item, 'Age restrictions')
        scratch.marker = item.xpath('guid').text
        scratch.url = item.xpath('link').text
        scratch.venue_id = venue.id
        permanent = Event.find_by_marker(scratch.marker)
        e = Event.comparison(scratch, permanent)
        @events << e
      end
      @events.reject!{|event| event.nil? }
      @events
    end
  end

  class Midwestix
    def self.gather(venue)
      #go to the page with all the goddamn links we have to follow
      index = Nokogiri::HTML(open(venue.event_list_url))

      @events = []

      index.xpath("//a[text()='buy tickets']").map do |node| 
        item = Nokogiri::HTML(open("#{node.attributes['href'].text}"))
        scratch = Event.create!
        scratch.venue_id = venue.id
        scratch.name = item.xpath("//div[@class='EventInfoItemEventName ItemName']").text
        scratch.description = ""
        unless item.xpath("//div[@class='EventInfoItemSupportingText']").text == ""
          scratch.description += item.xpath("//div[@class='EventInfoItemSupportingText']").text+" : "
        end
        scratch.description += item.xpath("//div[@class='EventInfoShortDescription']").text
        begin
          scratch.begins_at = DateTime.parse(item.xpath("//div[@class='EventInfoItemDateTime']").text)
        rescue 
          p "Date was not properly parsed."
        end
        scratch.description += "\n"+item.xpath("//div[@class='EventInfoDateTimeSecondaryText']").text
        scratch.price = ""
        scratch.age_restriction = ""
        scratch.url = "http://events.midwestix.com/#{node.attributes['href'].text}"
        scratch.marker = node.attributes['href'].text
        permanent = Event.find_by_marker(scratch.marker)
        e = Event.comparison(scratch, permanent)
        @events << e

      end
      @events.reject!{|event| event.nil? }
      
      @events
    end
  end

  class TicketFly
    def self.gather(venue)

      @events = []
      fresh = 0
      Nokogiri::XML(open(venue.event_list_url+"&maxResults=200")).xpath("map/entry[@key='events']/map").map do |node|
        scratch = Event.create!
        scratch.venue_id = venue.id
        scratch.marker = node.xpath("entry[@key='id']").text
        scratch.name = node.xpath("entry[@key='name']").text
        scratch.description = node.xpath("entry[@key='headliners']/map/entry[@key='eventDescription']").text
        scratch.age_restriction = node.xpath("entry[@key='ageLimit']").text
        scratch.begins_at = DateTime.parse(node.xpath("entry[@key='startDate']").text)
        scratch.price = node.xpath("entry[@key='ticketPrice']").text
        scratch.url = "http://www.ticketfly.com/event/#{scratch.marker}"
        permanent = Event.find_by_marker(scratch.marker)
        e = Event.comparison(scratch, permanent)
        @events << e
        
      end
      @events.reject!{|event| event.nil? }

      @events

    end
  end
    
  
  def self.next_sunday
    unless(Date.today.cwday == 7)
      days = (0..6).map{|x| Date.today + x}
      sunday = days.select{|day| day.cwday == 7}.first
    else
      sunday = Date.today
    end
    sunday
  end
=begin  
  def self.price_helper(price_text, event_id)
    
    price = price_text.scan(/\$(\d+)/).flatten
    if(price.empty?)
      price = price_text.scan(/(Free|FREE)/).flatten
    end
    prices = []
    price.each do |p|
      p "Creating price #{p} for Event #{event_id}"
      prices << Price.create!(:amount=>p,:event_id=>event_id)
    end
    prices
  end
=end
  def self.price_helper(price)
    if price.scan(/\$(\d+)/).flatten.length != 0
      s = price.scan(/\$(\d+)/).flatten.map{|y| "$"+y}.join("-")
    else
      s = price
    end
    s
  end

  def self.age_helper(age)
    if age.scan(/(19|21)/).flatten.length != 0
      s = age.scan(/(19|21)/).flatten[0]+"+"
    else
      s = age
    end
    s
  end

  #Helper method for gigpress feeds
  def self.xml_wrap(item, text)
    #might be multiple cdata nodes in description node
    cdata = Nokogiri::XML(item.xpath("description").children.first.text)
    #cdata.xpath(".//li/strong[text()='Time:']/..").children[1].text
    wrapper = cdata.xpath(".//li/strong[text()='#{text}:']/..")
    wrapper.xpath(".//strong[text()='#{text}:']").remove
    wrapper.text.strip
  end
  
  def name
    self[:name] ||= self[:scraped_name]
  end
  
  def self.comparison(scratch, permanent)
    if(permanent.nil?)
      #If no event with this marker exists, go ahead and save everything.
      scratch.save!
      scratch
    else
      #update the already existing object
      permanent.examine
      ['name', 'description','age_restriction','price','begins_at'].each do |a| 
        if scratch[a] != permanent[a]
          permanent[a] = scratch[a]
          permanent.change
        end 
      end

      scratch.destroy
      permanent.save!
      permanent
    end
  end
  private
    def default_values
      self.state ||= "new"
    end
  
      
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if(@venue)
      @events = @venue.events.order("events.begins_at ASC")
    else
      @events = Event.order("events.begins_at ASC")
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def today
    if(@venue)
      @events = @venue.events.today
    else
      @events = Event.today
    end
  end

  def week
    if(@venue)
      @events = @venue.events.week.order("events.begins_at ASC")
    else
      @events = Event.week.order("events.begins_at ASC")
    end
    render('index')
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.create(params[:event])
    if (@event.venue_id.nil? and params[:venue_id])
      @event.venue_id = params[:venue_id]
    end
    @event.date = "#{params[:year]}-#{params[:month]}-#{params[:day]}".to_date
    if @event.save and @event.venue_id  
      flash[:notice] = "Event created successfully."
      redirect_to(:action => "index")
    else
      render('new')
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    p params.inspect
    #@event.prices.destroy_all
    if @event.update_attributes(params[:event])
      @event.save
      flash[:notice] = "Event updated successfully."
      redirect_to(:action => 'unconfirmed')
    else
      render('edit')
    end
  end

  def delete
    @event = Event.find(params[:id])
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:notice] = "Event successfully destroyed."
    redirect_to(:action => 'index')
  end
  
  def scrape
    Delayed::Job.enqueue(ScrapingJob.new())
    flash[:notice] = "Scrape initiated."
  end
  
  def unconfirmed
    if(@venue)
      @events = @venue.events.unconfirmed
    else
      @events = Event.unconfirmed
    end
  end
  
  def confirm
    @event = Event.find(params[:id])
  end
  
  
  before_filter :load_venues, :only => [:new, :edit]
  before_filter :find_venue
  protected
  def load_venues
    @venues_arr = Venue.all.map{|venue| [venue.name, venue.id] }
  end
  
  def find_venue
    if(params[:venue_id])
      @venue = Venue.find(params[:venue_id])
    end   
  end
  

end

app/helpers/events_helper.rb
module EventsHelper
  
  def am_pm(time)
    str = (time.hour > 12)? "#{time.hour % 12} PM": "#{time.hour % 12} AM"
  end
  
  def event_day(event_date)
    if(event_date.month == Date.today.month && event_date.mday == Date.today.mday)
      str = "Today"
    else
      str = event_date.strftime("%a")
    end
    str
  end
  
  def event_day_indiv(event_date)
    if(event_date.month == Date.today.month && event_date.mday == Date.today.mday)
      str = "Today"
    else
      str = event_date.strftime("%a")
    end
    str
  end
  
  def short_price(prices)
    arr = []
    prices.each do |price|
      arr << price.amount
    end
    price = arr.join(" / ")
  end
  
  
end

app/views/events/confirm.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="event confirm">
	<h2>Confirm Event</h2>
	
	<%= nested_form_for @event do |event_form| %>

				<h3>Scraped Information</h3>
				<p><strong>Scraped Name: </strong><%= @event.scraped_name %></p>
				<p><strong>Scraped Age Info: </strong><%= @event.scraped_age %></p>
				
				
				
				<div class='leftcol'>
					<div id="name">
						<%= label :event_name,"Name", :class => "prime" %>
						<%= event_form.text_field(:name)%>
					</div>
					<div id="age">
						<%= label :event, "Age Restriction", :class => "prime" %>
				
						<%= event_form.radio_button(:age_restriction, "All Ages")%> <%= label :age_all, "All Ages"%>
						<%= event_form.radio_button(:age_restriction, "19+")%> <%= label :age_19, "19+"%>
						<%= event_form.radio_button(:age_restriction, "21+")%> <%= label :age_21, "21+"%>
					</div>
					<div id="description">
						<%= label :event, "Description", :class => "prime" %>
						<%= event_form.text_area(:description, :size=>"50x10")%>
					</div>
					<div id="time">
						<%= label :event, "Date & Time", :class => "prime" %>
						<%= event_form.datetime_select(:begins_at) %>
					</div>
					<div id="prices">
						<%= label :event, "Price/Description", :class => "prime" %>
						
						<%= event_form.fields_for :prices do |price_form| %>

							<%= price_form.text_field(:amount)%><%= price_form.text_field(:description)%><%= price_form.link_to_remove "Remove this Price"%>
				
						<% end %>
						<%= event_form.link_to_add "Add a Price", :prices %>
					</div>
					<div id="venue">
						<%= label :event, "Venue", :class => "prime" %>
						<%= event_form.collection_select(:venue_id, Venue.all, :id, :display_name)%>
					</div>
				
					<div id="confirmation">
						<%= label :event, "Confirmed", :class => "prime" %>
				
						<%= event_form.radio_button(:confirmed, "0" ) %> <%= label :confirmed_no, "No"%>
						<%= event_form.radio_button(:confirmed, "1" ) %> <%= label :confirmed_yes, "Yes"%>
					</div>
					<%= submit_tag("Update Event")%>
				</div>
		

			

		
	<% end %>
	
	
	<% unless @event.url.nil? %>
	<iframe src=<%= @event.url %>  />
	<% end %>
</div>

app/views/events/delete.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="event show">
	<h2>Show Event</h2>
	<table summary="event detail view">
		<tr>
			<th>Name</th>
			<td><%= @event.name%></td>
		</tr>
		<tr>
			<th>Venue</th>
			<td><%= @event.venue.name%></td>
		</tr>
		<tr>
			<th>Time</th>
			<td><%= @event.time %></td>
		</tr>
		<tr>
			<th>Description</th>
			<td><%= @event.description %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= @event.price %></td>
		</tr>
		<tr>
			<th>Age Restriction</th>
			<td><%= @event.age_restriction %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @event.created_at %></td>
		</tr>
		<tr>
			<th>Updated</th>
			<td><%= @event.updated_at %></td>
		</tr>
	</table>
	
	<%= link_to("Delete this event", {:action => 'destroy'}, :method => :delete) %>
	
</div>

app/views/events/edit.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="event edit">
	<h2>Edit Event</h2>
	
	<%= nested_form_for @event do |event_form| %>
		<table summary="event form fields">
			<tr>
				<th>Scraped Name</th>
				<td class="scraped_name"><%= @event.scraped_name %></td>
			</tr>
			<tr>
				<th>Name</th>
				<td><%= event_form.text_field(:name)%> </td>
			</tr>
				<th>Scraped Age Info</th>
				<td><%= @event.scraped_age %></td>
			</tr>
			<tr>
				<th>Age Restriction</th>
				<td>
					<%= event_form.radio_button(:age_restriction, "All Ages")%> <%= label :age_all, "All Ages"%>
					<%= event_form.radio_button(:age_restriction, "19+")%> <%= label :age_19, "19+"%>
					<%= event_form.radio_button(:age_restriction, "21+")%> <%= label :age_21, "21+"%>
				</td>
			</tr>
			<tr>
				<th>Description</th>
				<td><%= event_form.text_area(:description, :size=>"50x10")%></td>
			</tr>

			<tr>
				<th>Date/Time</th>
				<td>
					<%= event_form.datetime_select(:begins_at) %>
				</td>
			<tr>
			<tr>
				<th>Price/Description</th>
			<% event_form.fields_for :prices do |price_form| %>

				<td><%= price_form.text_field(:amount)%><%= price_form.text_field(:description)%></td>
				
			
			<% end %>
			</tr>
			<tr>
				<th>Venue</th>
				<td><%= event_form.collection_select(:venue_id, Venue.all, :id, :display_name)%></td>
			</tr>
			<tr>
				<th>Confirmed</th>
				<td>	
						<%= event_form.radio_button(:confirmed, "0" ) %> <%= label :confirmed_no, "No"%>
						<%= event_form.radio_button(:confirmed, "1" ) %> <%= label :confirmed_yes, "Yes"%>
				</td>
		</table>
		

			<%= submit_tag("Update event")%>

		
	<% end %>
	
	
	<% unless @event.url.nil? %>
	<iframe src=<%= @event.url %> width=100% height=500px style="margin-top:50px">
	<% end %>
</div>

app/views/events/index.html.erb
<div class="wrapper">
<% if @venue %>
	<h1><%= @venue.name %></h1>
<%
	else
%>
	<h1>Events in Iowa City</h1>
<%
		mixed = true
		cur_day = ""
	end 
%>
<div class="events">
	<% altswitch = false %>
	<% @events.each do |event| %>
		<% 
			item = (altswitch)? "'item alt'" : "'item'" 
			altswitch = !altswitch
		%>
		<% if mixed && event_day(event.begins_at) != cur_day %>
			<div class="header"><%= event.begins_at.strftime("%A, %B #{event.begins_at.day.ordinalize}")%></div>
		<% 
				cur_day = event_day(event.begins_at)
			 end 
		%>
		<div class=<%= item %> onclick=<%="window.location='#{event_path(event.id)}'"%>>
			<div class="bullet">
				<ul>
					<li class="bullet day venue">
						<%= (mixed)? event.venue.display_name : event_day(event.begins_at)%>
					</li>
					<li class='price date bullet'>
						<%= 
						(mixed)? Event.price_helper(event.price) : event.begins_at.strftime("%b #{event.begins_at.day.ordinalize}") %>
					</li>
					<li class='time bullet'>
						<%= am_pm(event.begins_at) %>
					</li>
				</ul>
			</div>
			<div class='info'>


				<h2 class='event title'><%= event.name %></h2>
				<p class='description'><%= (event.description == "")? "No more info available." : event.description %></p>
				<div class="details">
					<ul>
						<li class='event age'><%= Event.age_helper(event.age_restriction) %></li>
						<li class='price'><%= Event.price_helper(event.price)[0,20] %></li>
					</ul>
				</div>
				

			</div>
	
		</div>
	<% end %>

</div>
</div>
<!--ul class="navigation">
	<li><%= link_to("This Week", week_events_path()) %></li>
	<li><%= link_to("Venue List", venues_path()) %></li>
</ul-->

app/views/events/new.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="event new">
	<h2>New Event<%= @venue? " at #{@venue.name}" : ''%></h2>
	
	<%= form_for(:event, :url => {:action => "create", :id => @event.id}) do |f| %>
		<table summary="event form fields">
			<tr>
				<th>Name</th>
				<td><%= f.text_field(:name)%></td>
			</tr>
			<tr>
				<th>Description</th>
				<td><%= f.text_field(:description)%></td>
			</tr>

			<tr>
				<th>Date/Time</th>
				<td>
					<%= f.datetime_select(:begins_at) %>

				</td>
			<tr>
				<th>Price</th>
				<td><%= f.text_field(:price)%></td>
			</tr>
			<tr>
				<th>Age Restriction</th>
				<td><%= f.text_field(:age_restriction)%></td>
			</tr>
			<tr>
				<th>Venue</th>
				<td><%= !@venue? f.select(:venue_id, options_for_select(@venues_arr)) : "#{@venue.name}"%>
			</tr>
		</table>
			
		<div class="form-buttons">
			<%= submit_tag("Create event")%>
		</div>
		
	<% end %>
	
</div>

app/views/events/scrape.html.erb
<% if !flash[:notice].blank? %>
	<div class="notice">
		<%= flash[:notice]%>
	</div>
<% end %>

app/views/events/show.html.erb
<div class="individual">

	<h1><%= @event.name%></h1>

	<h2><%= link_to( "@ #{@event.venue.name}", @event.venue.site_url) %></h2>

		<ul>
			<!--<li><%= event_day_indiv(@event.begins_at) %></li>-->
			<li><%= @event.begins_at.strftime("%b #{@event.begins_at.day.ordinalize}") %></li>

			<li><%= Event.price_helper(@event.price) %></li>
			<li><%= Event.age_helper(@event.age_restriction) %></li>
		</ul>

	<p><%= (@event.description == "")? "No more info available." : @event.description %></p>

</div>

app/views/events/today.html.erb
<div data-role="page">

    <div data-role="header" data-theme="b">
        <h1>Events<%= @venue? link_to(" at #{@venue.name}", venue_path(@venue.id)) : ''%> Today, <%= Date.today.strftime("%a %m/%d")%></h1>
				
    </div>

    <div data-role="content" data-theme="b">
				<p></p>
        <ul data-role="listview" data-inset="false">
				<li data-role="list-divider"><%= @events.first.venue.name%></li>
				<% cur_venue = @events.first.venue.name%>
				<% @events.each do |event| %>
					<% if event.venue.name != cur_venue%>
						<li data-role="list-divider"><%= event.venue.name%></li>
					<% end %>
					<li>
						<% event_name = raw event.name%>
						<h1><%= link_to( event_name, event_path(event.id)) %></h1>
						<p><%= raw event.price %></p>
						<h2 class="ui-li-aside">
							<%= (event.begins_at.hour > 12)? "#{event.begins_at.hour % 12} PM": "#{event.begins_at.hour % 12} AM" %>
							<% if (event.age_restriction != "")%>
							 <%= " / " + event.age_restriction %>	
							<% end %>
						</h2>
					</li>
				<% end %>
					<li data-role="list-divider"></li>
				</ul>
				<p></p>
    </div>

		<div data-role="footer" data-theme="b">
			<div data-role="navbar" data-theme="b">
				<ul>
					<li><%= link_to("This Week", week_events_path()) %></li>
					<li><%= link_to("Venue List", venues_path()) %></li>
				</ul>
			</div>
		</div>
</div>

app/views/events/unconfirmed.html.erb
<h1>Unconfirmed Events</h1>
<table class="unconfirmed">
	<th>Event Name</th>
	<th>Venue</th>
	<th>Action</th>
<% @events.each do |event| %>
	<tr>
		<td class='name'><%= event.scraped_name %></td>
		<td class='venue'><%= event.venue.name %></td>
		<td class='action'><%= link_to "Confirm", confirm_event_path(event.id) %></td>
	</tr>
	
<% end %>
</table>

app/views/events/week.html.erb
<div data-role="page">

    <div data-role="header" data-theme="b" data-position="fixed">
        <h1>Events<%= @venue? link_to(" at #{@venue.name}", venue_path(@venue.id)) : ' In Iowa City'%> This Week</h1>
    </div>

    <div data-role="content" data-theme="b">
        <ul data-role="listview" data-inset="false">
				<li data-role="list-divider"><%= @events.first.begins_at.strftime("%A")%></li>
					<% cur_day = @events.first.begins_at.wday %>
					<% @events.each do |event| %>
						<%
						if (event.begins_at.wday != cur_day)
							cur_day = event.begins_at.wday
						%>
						<li data-role="list-divider"><%= event.begins_at.strftime("%A")%></li>
					<% end %>
					<li>
						<% event_name = raw event.name%>
						<h1><%= link_to( event_name, event_path(event.id)) %></h1>
						<p><strong><%= event.venue.name %></strong></p> 
						<p><%= raw event.price %></p>
						<h2 class="ui-li-aside">	
							<%= (event.begins_at.hour > 12)? "#{event.begins_at.hour % 12} PM": "#{event.begins_at.hour % 12} AM" %>
							<% if (event.age_restriction != "")%>
							 <%= "/" + event.age_restriction %>	
							<% end %>
						</h2>
					</li>
					<% end %>
					<li data-role="list-divider"></li>
				</ul>
    </div>

		<div data-role="footer" data-theme="b" data-position="fixed">
			<div data-role="navbar" data-theme="b">
				<ul>
					<li><%= link_to("Today", today_events_path()) %></li>
					<li><%= link_to("Venue List", venues_path()) %></li>
				</ul>
			</div>
		</div>
</div>