config/routes.rb
Onesheet::Application.routes.draw do

  
 
    
  resources :statuses

  root :to => "events#week"
  
  resources :venues do
    collection do
      
    end
    
    member do
    end
    
    resources :events do
      collection do
        get :today
        get :week
      end
    end
  
  end
  
  resources :events do
    collection do
      get :today
      get :scrape
      get :week
    end
    member do
    end
  end
  
  
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/venue.rb
class Venue < ActiveRecord::Base

  has_many :events
  
  def flush_events
    self.events.past.destroy_all
  end
  

  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.order("venues.name asc")
  end

  def show
    @venue = Venue.find(params[:id])
  end
  
  def new
    @venue = Venue.new
  end
  
  def create
    @venue = Venue.new(params[:venue])
    if @venue.save
      flash[:notice] = "Venue Created successfully."
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end
    
  def edit
    @venue = Venue.find(params[:id])
  end
  
  def update
    @venue = Venue.find(params[:id])
    if @venue.update_attributes(params[:venue])
      flash[:notice] = "Venue updated successfully."
      redirect_to(:action=>'show', :id => @venue.id)
    else
      render('edit')
    end
  end
  
  def delete
    @venue = Venue.find(params[:id])
  end
  
  def destroy
    Venue.find(params[:id]).destroy
    flash[:notice] = "Venue destroyed successfully."
    redirect_to(:action => "index")
  end
  
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/delete.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="venue show">
	<h2>Delete this venue</h2>
	<table summary="venue detail view">
		<tr>
			<th>Name</th>
			<td><%= @venue.name%></td>
		</tr>
		<tr>
			<th>Address</th>
			<td><%= @venue.address%></td>
		</tr>
		<tr>
			<th>Site</th>
			<td><%= @venue.site_url %></td>
		</tr>
		<tr>
			<th>Event List</th>
			<td><%= @venue.event_list_url %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @venue.created_at %></td>
		</tr>
		<tr>
			<th>Updated</th>
			<td><%= @venue.updated_at %></td>
		</tr>
	</table>
	
	<%= link_to "Delete", {:action => "destroy"}, :method => :delete %>
		
</div>

app/views/venues/edit.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="venue new">
	<h2>Edit venue</h2>
	
	<%= form_for @venue do |f| %>
		<table summary="venue form fields">
			<tr>
				<th>Name</th>
				<td><%= f.text_field(:name)%></td>
			</tr>
			<tr>
				<th>Address</th>
				<td><%= f.text_field(:address)%></td>
			</tr>
			<tr>
				<th>Site</th>
				<td><%= f.text_field(:site_url)%></td>
			</tr>
			<tr>
				<th>Event List</th>
				<td><%= f.text_field(:event_list_url)%></td>
			</tr>
			<tr>
				<th>Display Name</th>
				<td><%= f.text_field(:display_name)%></td>
			</tr>
			
		</table>
		
		<div class="form-buttons">
			<%= submit_tag("Update venue")%>
		</div>
		
	<% end %>
	
</div>

app/views/venues/index.html.erb
<div data-role="page" data-theme="d">
	<div data-role="header" data-theme="d">
		<h1>Venues</h1>
	</div>
	
	<div data-role="content" date-theme="d">
		<ul data-role="listview">
		<% @venues.each do |venue| %>
		
			<li>
				<h1><%= link_to(venue.name, venue_path(venue.id)) %></h1>
				<p><%= venue.address %></p>
			</li>
		
		<% end %>
		</ul>
	<div>
</div>

app/views/venues/new.html.erb
<%= link_to("<< Back to List", {:action  => 'index'}, :class  => 'back-link')%>

<div class="venue new">
	<h2>Edit venue</h2>
	
	<%= form_for(:venue, :url => {:action => "create", :id => @venue.id}) do |f| %>
		<table summary="venue form fields">
			<tr>
				<th>Name</th>
				<td><%= f.text_field(:name)%></td>
			</tr>
			<tr>
				<th>Address</th>
				<td><%= f.text_field(:address)%></td>
			</tr>
			<tr>
				<th>Site</th>
				<td><%= f.text_field(:site_url)%></td>
			</tr>
			<tr>
				<th>Event List</th>
				<td><%= f.text_field(:event_list_url)%></td>
			</tr>

			
		</table>
		
		<div class="form-buttons">
			<%= submit_tag("Create venue")%>
		</div>
		
	<% end %>
	
</div>

app/views/venues/show.html.erb
<div data-role="page" data-theme="d">
	<div data-role="header" data-theme="d">
		<h2>Venue</h2>
	</div>
	<div data-role="content">
	<table summary="venue detail view">
		<tr>
			<th>Name</th>
			<td><%= @venue.name%></td>
		</tr>
		<tr>
			<th>Address</th>
			<td><%= @venue.address%></td>
		</tr>
		<tr>
			<th>Site</th>
			<td><%= @venue.site_url %></td>
		</tr>
		<tr>
			<th>Display Name</th>
			<td><%= @venue.display_name %></td>
		</tr>
		
	</table>
	</div>
	<div data-inline="true">
		<%= link_to "Event List", venue_events_path(@venue.id), :"data-role"=>"button" %>
	</div>
	
</div>